# Generated by Django 3.0.5 on 2020-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
    ]
